// Kho nhận xét lớp 1
const KHO_LOP1 = {
  'Tiếng Việt_xuat_sac': [
    'Đọc trơn tru, viết đúng mẫu chữ, nắm chắc các âm vần và hoàn thành xuất sắc các bài tập Tiếng Việt.',
    'Nhận biết và đọc đúng các âm vần đã học, viết chữ đẹp và trình bày bài sạch sẽ, cẩn thận.',
    'Đọc thành thạo các bài tập đọc, viết đúng chính tả và có ý thức luyện chữ viết rất tốt.',
    'Nắm vững các âm vần, đọc rõ ràng lưu loát và viết đúng mẫu chữ quy định.',
    'Tiếp thu nhanh các âm vần mới, đọc trôi chảy và viết chữ đúng mẫu, sạch đẹp.',
    'Học tốt môn Tiếng Việt, đọc đúng và viết đẹp, hoàn thành xuất sắc các yêu cầu của lớp 1.',
  ],
  'Tiếng Việt_tot': [
    'Đọc đúng các âm vần đã học, viết chữ tương đối đẹp và hoàn thành tốt bài tập được giao.',
    'Nắm được các âm vần cơ bản, đọc rõ ràng và viết đúng chính tả trong các bài học.',
    'Đọc và viết đạt yêu cầu, có cố gắng luyện chữ và hoàn thành bài tập đầy đủ.',
    'Biết đọc các bài tập đọc ngắn, viết đúng mẫu và trình bày bài viết gọn gàng.',
    'Học tập tích cực, đọc đúng và viết khá đẹp, có tiến bộ rõ rệt trong học kỳ.',
  ],
  'Tiếng Việt_hoan_thanh': [
    'Đọc được các âm vần cơ bản, viết đúng nhưng cần rèn thêm tốc độ và sự cẩn thận.',
    'Hoàn thành các yêu cầu cơ bản môn Tiếng Việt, cần luyện thêm chữ viết và chính tả.',
    'Đọc và viết đạt mức cơ bản, cần chú ý hơn trong việc luyện đọc và rèn chữ viết.',
    'Cơ bản nắm được các âm vần, cần cố gắng thêm để đọc trôi chảy và viết đẹp hơn.',
  ],
  'Tiếng Việt_chua_hoan_thanh': [
    'Cần luyện tập thêm để đọc đúng các âm vần và viết đúng mẫu chữ theo yêu cầu.',
    'Chưa đọc thành thạo, cần được hỗ trợ thêm trong việc nhận biết âm vần và luyện viết.',
    'Cần cố gắng hơn trong học Tiếng Việt, chú ý luyện đọc và rèn chữ viết mỗi ngày.',
  ],

  'Toán_xuat_sac': [
    'Thực hiện thành thạo các phép tính trong phạm vi đã học, giải toán nhanh và chính xác.',
    'Nắm vững các số và phép tính, làm bài đúng và nhanh, có tư duy toán học tốt.',
    'Tính toán chính xác, nhận biết tốt các hình học cơ bản và hoàn thành xuất sắc bài tập Toán.',
    'Hiểu sâu kiến thức Toán lớp 1, vận dụng linh hoạt vào giải các bài toán có lời văn.',
    'Làm tính đúng, nhanh và biết giải toán có lời văn rõ ràng, trình bày sạch đẹp.',
    'Nắm chắc các phép cộng trừ trong phạm vi đã học, tư duy logic tốt và làm bài cẩn thận.',
  ],
  'Toán_tot': [
    'Thực hiện đúng các phép tính cơ bản, hoàn thành tốt bài tập và có tiến bộ trong học kỳ.',
    'Nắm được các số và phép tính đã học, làm bài đúng yêu cầu và trình bày rõ ràng.',
    'Tính toán khá chính xác, biết giải toán đơn giản và hoàn thành bài tập đầy đủ.',
    'Hiểu bài và làm đúng các dạng toán cơ bản, cần rèn thêm tốc độ tính toán.',
    'Học tốt môn Toán, làm bài cẩn thận và có ý thức kiểm tra lại kết quả.',
  ],
  'Toán_hoan_thanh': [
    'Thực hiện được các phép tính cơ bản, cần luyện thêm để tính nhanh và chính xác hơn.',
    'Hoàn thành yêu cầu môn Toán, cần chú ý hơn trong việc đọc đề và trình bày bài.',
    'Cơ bản nắm được các phép tính, cần cố gắng thêm để làm bài đúng và nhanh hơn.',
    'Đạt yêu cầu cơ bản môn Toán, cần rèn luyện thêm để nâng cao kết quả học tập.',
  ],
  'Toán_chua_hoan_thanh': [
    'Cần ôn luyện thêm các phép tính cơ bản, chú ý rèn luyện mỗi ngày để tiến bộ hơn.',
    'Chưa nắm vững các phép tính, cần được hỗ trợ thêm và luyện tập thường xuyên.',
    'Cần cố gắng hơn trong học Toán, chú ý nghe giảng và hoàn thành đầy đủ bài tập.',
  ],

  'Đạo đức_tot': [
    'Có ý thức thực hiện nội quy lớp học, lễ phép với thầy cô và hòa đồng với bạn bè.',
    'Thực hiện tốt các quy tắc ứng xử, biết quan tâm giúp đỡ bạn và giữ gìn vệ sinh.',
    'Ngoan ngoãn, chăm chỉ và có ý thức rèn luyện đạo đức theo yêu cầu của lớp.',
    'Biết vâng lời thầy cô, thân thiện với bạn bè và hoàn thành tốt nhiệm vụ được giao.',
    'Luôn thực hiện tốt nội quy lớp học, lễ phép với thầy cô và thân thiện với bạn bè.',
    'Có ý thức kỷ luật tốt, biết giúp đỡ bạn bè và thực hiện đúng các quy tắc ứng xử.',
    'Ngoan ngoãn, lễ phép, biết vâng lời thầy cô và có tinh thần đoàn kết với bạn bè.',
    'Luôn giữ gìn vệ sinh, bảo vệ của công và có ý thức xây dựng tập thể lớp tốt.',
    'Biết nhường nhịn bạn bè, không tranh giành và luôn giữ thái độ vui vẻ, hòa nhã.',
    'Có ý thức giữ gìn đồ dùng học tập, không làm hỏng tài sản chung của lớp.',
    'Biết chào hỏi lễ phép khi gặp người lớn, thể hiện nếp sống văn minh tốt.',
    'Tích cực tham gia các hoạt động tập thể, biết chia sẻ và quan tâm đến bạn bè.',
    'Có hành vi đúng mực trong lớp học, không gây ồn ào và tôn trọng giờ học.',
    'Biết nhận lỗi khi làm sai và có ý thức sửa chữa, không tái phạm.',
    'Thực hiện tốt các nội quy trường lớp, đi học đúng giờ và mang đầy đủ đồ dùng.',
    'Biết bảo vệ môi trường, không xả rác bừa bãi và nhắc nhở bạn cùng thực hiện.',
    'Có thái độ học tập nghiêm túc, không nói chuyện riêng và chú ý nghe giảng.',
    'Biết giúp đỡ bạn khi gặp khó khăn, thể hiện tinh thần tương thân tương ái.',
    'Thực hiện đúng các quy định về an toàn giao thông khi đến trường.',
    'Có ý thức tiết kiệm điện nước, giữ gìn tài sản chung và bảo vệ của công.',
    'Biết kính trọng người lớn tuổi, yêu thương em nhỏ và đoàn kết với bạn bè.',
    'Luôn trung thực trong học tập, không quay cóp và tự giác làm bài.',
    'Có tinh thần trách nhiệm với công việc được giao, hoàn thành đúng hạn.',
    'Biết xếp hàng trật tự, không chen lấn và thực hiện tốt nề nếp lớp học.',
    'Thể hiện lòng biết ơn thầy cô và cha mẹ qua hành động và lời nói hàng ngày.',
    'Có ý thức giữ gìn sách vở sạch sẽ, không vẽ bậy và bảo quản đồ dùng tốt.',
    'Biết chia sẻ đồ dùng với bạn khi cần, thể hiện tinh thần giúp đỡ lẫn nhau.',
    'Thực hiện tốt năm điều Bác Hồ dạy, có ý thức rèn luyện đạo đức hàng ngày.',
    'Biết nói lời cảm ơn và xin lỗi đúng lúc, thể hiện văn hóa ứng xử tốt.',
    'Có ý thức bảo vệ cây xanh, không bẻ cành và giữ gìn cảnh quan trường lớp.',
  ],
  'Đạo đức_hoan_thanh': [
    'Cơ bản thực hiện được các yêu cầu môn Đạo đức, cần rèn luyện thêm ý thức kỷ luật.',
    'Hoàn thành yêu cầu môn học, cần chú ý hơn trong việc giữ gìn vệ sinh và nội quy lớp.',
    'Đạt yêu cầu cơ bản, cần cố gắng thêm để thực hiện tốt hơn các quy tắc ứng xử.',
    'Cơ bản ngoan ngoãn, cần rèn thêm thói quen lễ phép và chào hỏi đúng mực.',
    'Hoàn thành các yêu cầu cơ bản, cần chú ý hơn trong việc giữ trật tự giờ học.',
    'Đã thực hiện được nội quy lớp, cần cố gắng thêm trong việc giúp đỡ bạn bè.',
    'Cơ bản có ý thức kỷ luật, cần rèn luyện thêm để thực hiện đều đặn hơn.',
    'Hoàn thành yêu cầu môn Đạo đức, cần chú ý hơn đến việc giữ gìn của công.',
    'Đạt mức cơ bản, cần tích cực hơn trong các hoạt động tập thể của lớp.',
    'Cơ bản thực hiện tốt nội quy, cần rèn thêm ý thức tự giác trong học tập.',
  ],
  'Đạo đức_chua_hoan_thanh': [
    'Cần chú ý hơn trong việc thực hiện nội quy và rèn luyện các hành vi đạo đức.',
    'Cần cố gắng hơn trong việc giữ gìn kỷ luật và thực hiện đúng các quy tắc lớp học.',
    'Cần rèn luyện thêm ý thức kỷ luật, chú ý giữ trật tự và lễ phép với thầy cô.',
    'Cần được nhắc nhở thêm về nội quy lớp học và ý thức giữ gìn vệ sinh chung.',
    'Cần cố gắng nhiều hơn trong việc thực hiện các quy tắc ứng xử và đạo đức.',
  ],

  'TN-XH_tot': [
    'Nắm được các kiến thức cơ bản về tự nhiên xã hội, biết vận dụng vào thực tế cuộc sống.',
    'Tích cực tham gia các hoạt động khám phá, nắm được nội dung bài học và trình bày khá rõ.',
    'Hiểu bài và trả lời được các câu hỏi cơ bản, có ý thức quan sát môi trường xung quanh.',
    'Học tốt môn TN-XH, biết liên hệ kiến thức với cuộc sống và hoàn thành tốt bài tập.',
    'Biết quan sát và nhận biết các sự vật hiện tượng xung quanh, trả lời câu hỏi rõ ràng.',
    'Nắm được kiến thức về bản thân, gia đình và trường học, biết vận dụng vào thực tế.',
    'Tích cực phát biểu trong giờ học, có nhiều hiểu biết về thế giới xung quanh.',
    'Biết nhận biết các loài cây, con vật quen thuộc và trình bày được đặc điểm của chúng.',
    'Hiểu được các hiện tượng thời tiết đơn giản, biết đặt câu hỏi và tìm hiểu.',
    'Biết giữ gìn sức khỏe, vệ sinh cá nhân và bảo vệ môi trường xung quanh.',
    'Nắm được các quy tắc an toàn cơ bản, biết ứng xử đúng trong các tình huống thường gặp.',
    'Biết phân biệt các nghề nghiệp phổ biến, hiểu được ích lợi của từng nghề trong xã hội.',
    'Có hiểu biết về các phương tiện giao thông, biết thực hiện an toàn khi tham gia giao thông.',
    'Biết tên và công dụng các bộ phận cơ thể, có ý thức giữ gìn sức khỏe.',
    'Hiểu được mối quan hệ gia đình, biết yêu thương và kính trọng ông bà, cha mẹ.',
    'Biết các quy tắc vệ sinh an toàn thực phẩm, có ý thức ăn uống đúng cách.',
    'Nắm được kiến thức về các mùa trong năm, biết đặc điểm từng mùa và cách ăn mặc phù hợp.',
    'Biết tên và vị trí các phòng trong trường, hiểu nội quy và cách sử dụng đúng.',
    'Có hiểu biết về các loại thực phẩm, biết phân biệt thực phẩm sạch và không an toàn.',
    'Biết các biểu hiện của thời tiết, có ý thức chuẩn bị trang phục phù hợp.',
    'Hiểu được tầm quan trọng của việc giữ gìn vệ sinh môi trường, biết thực hiện hàng ngày.',
    'Nắm được kiến thức về các loài động vật gần gũi, biết chăm sóc và bảo vệ chúng.',
    'Biết các địa danh quen thuộc trong địa phương, có tình yêu quê hương.',
    'Hiểu được các quy tắc an toàn khi ở nhà, biết xử lý các tình huống nguy hiểm đơn giản.',
    'Biết tên và công dụng các đồ dùng trong nhà, có ý thức sử dụng đúng cách.',
    'Có hiểu biết về các nguồn nước, biết tiết kiệm nước và giữ gìn nguồn nước sạch.',
    'Biết các loại cây trồng phổ biến, hiểu được ích lợi của cây xanh với môi trường.',
    'Nắm được kiến thức về các nghề truyền thống, có ý thức giữ gìn và phát huy.',
    'Biết các quy tắc ứng xử nơi công cộng, thực hiện tốt khi đi ra ngoài.',
    'Hiểu được tầm quan trọng của giấc ngủ và vận động, có ý thức rèn luyện sức khỏe.',
  ],
  'TN-XH_hoan_thanh': [
    'Nắm được kiến thức cơ bản môn TN-XH, cần tích cực quan sát và liên hệ thực tế hơn.',
    'Hoàn thành yêu cầu môn học, cần chú ý hơn trong giờ học và tích cực phát biểu.',
    'Đạt yêu cầu cơ bản, cần cố gắng thêm để hiểu sâu hơn về tự nhiên và xã hội.',
    'Cơ bản nắm được nội dung bài học, cần rèn thêm kỹ năng quan sát và trình bày.',
    'Hoàn thành các yêu cầu cơ bản, cần tích cực hơn trong việc tìm hiểu thế giới xung quanh.',
    'Đã nắm được kiến thức cơ bản, cần cố gắng thêm để trả lời câu hỏi rõ ràng hơn.',
    'Cơ bản hiểu bài, cần chú ý hơn trong việc liên hệ kiến thức với thực tế.',
    'Hoàn thành yêu cầu môn TN-XH, cần rèn thêm thói quen quan sát và ghi nhớ.',
    'Đạt mức cơ bản, cần tích cực hơn trong các hoạt động khám phá của lớp.',
    'Cơ bản nắm được kiến thức, cần cố gắng thêm để vận dụng vào thực tế tốt hơn.',
  ],
  'TN-XH_chua_hoan_thanh': [
    'Cần chú ý hơn trong giờ học TN-XH, tích cực quan sát và ghi nhớ kiến thức bài học.',
    'Cần cố gắng hơn, chú ý lắng nghe và tham gia tích cực các hoạt động học tập.',
    'Cần rèn luyện thêm thói quen quan sát, chú ý hơn đến các sự vật hiện tượng xung quanh.',
    'Cần được hỗ trợ thêm để nắm vững kiến thức TN-XH và biết vận dụng vào thực tế.',
    'Cần cố gắng nhiều hơn, tích cực tham gia bài học và hoàn thành đầy đủ bài tập.',
  ],

  'Âm nhạc_tot': [
    'Hát đúng giai điệu, thuộc lời bài hát và tham gia tích cực các hoạt động âm nhạc.',
    'Có cảm nhận âm nhạc khá tốt, hát đúng nhịp và hoàn thành tốt các yêu cầu môn học.',
    'Thuộc các bài hát đã học, hát rõ lời và tích cực tham gia hoạt động văn nghệ lớp.',
    'Học tốt môn Âm nhạc, biết vận động theo nhạc và hoàn thành tốt bài tập được giao.',
    'Hát đúng nhịp, thuộc lời và biết thể hiện cảm xúc qua bài hát một cách tự nhiên.',
    'Tích cực học hát, thuộc nhiều bài và biết gõ đệm theo nhịp khá chuẩn xác.',
    'Có giọng hát khá tốt, hát rõ lời và luôn hăng hái tham gia các tiết học âm nhạc.',
    'Biết lắng nghe âm nhạc và cảm nhận được giai điệu, hát đúng và đều.',
    'Hát được các bài hát trong chương trình, biết vận động phụ họa theo nhạc.',
    'Có cảm thụ âm nhạc tốt, hát đúng giai điệu và biết thể hiện sắc thái bài hát.',
    'Thuộc lời và hát đúng nhịp các bài hát đã học, tham gia nhiệt tình các hoạt động.',
    'Biết phân biệt các loại nhịp cơ bản, hát đúng và gõ đệm theo nhịp khá tốt.',
    'Hát to, rõ lời và đúng giai điệu, biết hòa giọng cùng các bạn trong lớp.',
    'Có ý thức luyện tập bài hát ở nhà, thuộc bài nhanh và hát đúng yêu cầu.',
    'Biết thể hiện niềm vui qua bài hát, hát hăng hái và tự tin trước lớp.',
    'Hát đúng giai điệu và biết vận động theo nhạc một cách nhịp nhàng.',
    'Có tai nghe nhạc tốt, hát đúng cao độ và trường độ các nốt nhạc.',
    'Tham gia tích cực các tiết học, hát đúng và biết lắng nghe bạn hát để hòa giọng.',
    'Thuộc nhiều bài hát thiếu nhi, hát vui tươi và thể hiện cảm xúc tốt.',
    'Biết gõ đệm theo lời ca, hát đúng nhịp và phối hợp tốt với các bạn.',
    'Hát đúng giai điệu, biết thể hiện tình cảm qua giọng hát và nét mặt.',
    'Có cảm nhận tốt về âm nhạc, hát đúng và biết nhận xét bài hát của bạn.',
    'Tham gia đầy đủ các hoạt động âm nhạc, hát nhiệt tình và đúng yêu cầu.',
    'Biết lắng nghe và cảm nhận âm nhạc, hát đúng giai điệu và rõ lời.',
    'Hát được các bài hát trong chương trình, biết vận động phụ họa sinh động.',
    'Có giọng hát trong sáng, hát đúng nhịp và luôn vui vẻ trong các tiết học.',
    'Thuộc lời bài hát, hát đúng giai điệu và biết thể hiện sắc thái vui tươi.',
    'Biết hát kết hợp vận động, thể hiện sự nhịp nhàng và tự tin trước lớp.',
    'Hát đúng và đều, biết phối hợp cùng các bạn trong các bài hát tập thể.',
    'Có ý thức học hát nghiêm túc, thuộc bài nhanh và hát đúng yêu cầu môn học.',
  ],
  'Âm nhạc_hoan_thanh': [
    'Hoàn thành các yêu cầu cơ bản môn Âm nhạc, cần luyện tập thêm để hát đúng và đều hơn.',
    'Thuộc bài hát cơ bản, cần rèn thêm để hát đúng nhịp điệu và thể hiện cảm xúc tốt hơn.',
    'Đạt yêu cầu môn học, cần tích cực hơn trong các tiết học và luyện tập bài hát ở nhà.',
    'Cơ bản thuộc bài hát, cần cố gắng thêm để hát đúng giai điệu và rõ lời hơn.',
    'Hoàn thành yêu cầu cơ bản, cần rèn thêm kỹ năng gõ đệm và vận động theo nhạc.',
    'Đã thuộc bài hát, cần luyện thêm để hát to, rõ lời và đúng nhịp hơn.',
    'Cơ bản hoàn thành bài hát, cần tích cực hơn trong việc tham gia các hoạt động.',
    'Hoàn thành môn Âm nhạc, cần chú ý hơn đến việc hát đúng cao độ và trường độ.',
    'Đạt mức cơ bản, cần cố gắng thêm để hát đều và biết vận động theo nhạc.',
    'Cơ bản thuộc lời bài hát, cần luyện thêm để hát đúng giai điệu và nhịp điệu.',
  ],
  'Âm nhạc_chua_hoan_thanh': [
    'Cần luyện tập thêm để hát đúng giai điệu và nhịp điệu theo yêu cầu môn Âm nhạc.',
    'Cần cố gắng hơn, chú ý nghe và luyện hát để đạt yêu cầu môn học.',
    'Cần thuộc lời bài hát và luyện tập thêm để hát đúng giai điệu.',
    'Cần tích cực hơn trong giờ học, chú ý lắng nghe và luyện hát để tiến bộ.',
    'Cần cố gắng nhiều hơn, luyện tập bài hát ở nhà để đạt yêu cầu môn Âm nhạc.',
  ],

  'Mĩ thuật_tot': [
    'Vẽ đúng yêu cầu, tô màu gọn gàng và có ý thức sáng tạo trong các bài học Mĩ thuật.',
    'Hoàn thành tốt các bài vẽ, biết phối màu và trình bày bài sạch sẽ, cẩn thận.',
    'Vẽ hình tương đối đúng, tô màu đẹp và hoàn thành bài tập đúng thời gian quy định.',
    'Học tốt môn Mĩ thuật, có ý thức sáng tạo và luôn cố gắng hoàn thiện bài vẽ.',
    'Vẽ hình cân đối, tô màu đều và biết sử dụng màu sắc hợp lý trong bài vẽ.',
    'Biết quan sát và vẽ lại các sự vật quen thuộc, tô màu gọn gàng và đẹp.',
    'Có ý thức sáng tạo trong từng bài vẽ, biết chọn màu sắc phù hợp với chủ đề.',
    'Vẽ đúng hình và tô màu đẹp, bài vẽ thể hiện sự cẩn thận và tự giác.',
    'Hoàn thành bài vẽ đúng hạn, biết phối màu và trình bày bài sạch đẹp.',
    'Có khiếu thẩm mỹ, vẽ hình cân đối và tô màu sáng tạo, bài vẽ luôn đẹp và ấn tượng.',
    'Biết vẽ các hình cơ bản đúng tỷ lệ, tô màu đều và không chạy ra ngoài.',
    'Tích cực tham gia giờ Mĩ thuật, có nhiều ý tưởng sáng tạo trong các bài vẽ.',
    'Vẽ được các hình theo yêu cầu, tô màu đẹp và trình bày bài gọn gàng.',
    'Biết phối hợp các màu sắc hài hòa, bài vẽ có bố cục rõ ràng và đẹp mắt.',
    'Có ý thức giữ gìn dụng cụ vẽ, sử dụng màu sắc đúng cách và tiết kiệm.',
    'Vẽ hình đúng mẫu, tô màu đều và biết thêm các chi tiết sáng tạo vào bài.',
    'Hoàn thành tốt các bài vẽ, biết nhận xét bài của bạn và rút kinh nghiệm.',
    'Biết vẽ theo cảm nhận riêng, tô màu sáng tạo và thể hiện cá tính trong bài.',
    'Có óc thẩm mỹ tốt, vẽ hình đẹp và biết sắp xếp bố cục hợp lý.',
    'Tô màu cẩn thận, không chạy ra ngoài và biết chọn màu phù hợp với nội dung.',
    'Vẽ được các hình đơn giản đúng tỷ lệ, tô màu đẹp và trình bày sạch sẽ.',
    'Biết vẽ theo chủ đề, tô màu hài hòa và hoàn thành bài đúng thời gian.',
    'Có sự tiến bộ rõ rệt trong các bài vẽ, biết vận dụng kỹ năng đã học.',
    'Vẽ hình có hồn, tô màu đẹp và biết thêm các chi tiết phụ làm phong phú bài vẽ.',
    'Biết sử dụng các dụng cụ vẽ đúng cách, tô màu đều và giữ gìn sạch sẽ.',
    'Hoàn thành bài vẽ đầy đủ, biết phối màu và thể hiện ý tưởng rõ ràng.',
    'Có ý thức học Mĩ thuật nghiêm túc, vẽ cẩn thận và hoàn thành đúng yêu cầu.',
    'Biết vẽ các hình khối cơ bản, tô màu đẹp và trình bày bài gọn gàng.',
    'Vẽ đúng hình và tô màu sáng tạo, bài vẽ thể hiện sự quan sát tinh tế.',
  ],
  'Mĩ thuật_hoan_thanh': [
    'Hoàn thành các bài vẽ theo yêu cầu, cần rèn thêm kỹ năng tô màu và sáng tạo.',
    'Đạt yêu cầu cơ bản môn Mĩ thuật, cần chú ý hơn trong việc vẽ hình và phối màu.',
    'Cơ bản hoàn thành bài vẽ, cần cố gắng thêm để vẽ đẹp và tô màu đều hơn.',
    'Hoàn thành bài vẽ đúng hạn, cần rèn thêm kỹ năng tô màu không chạy ra ngoài.',
    'Cơ bản vẽ được hình theo yêu cầu, cần cố gắng thêm để tô màu đẹp hơn.',
    'Đã hoàn thành bài vẽ, cần chú ý hơn đến việc chọn màu và phối màu hợp lý.',
    'Cơ bản đạt yêu cầu, cần rèn thêm để vẽ hình cân đối và tô màu đều hơn.',
    'Hoàn thành môn Mĩ thuật, cần tích cực hơn trong việc sáng tạo và thể hiện ý tưởng.',
    'Đạt mức cơ bản, cần cố gắng thêm để bài vẽ đẹp và sáng tạo hơn.',
    'Cơ bản hoàn thành bài vẽ, cần luyện thêm kỹ năng vẽ và tô màu.',
  ],
  'Mĩ thuật_chua_hoan_thanh': [
    'Cần cố gắng hơn trong các bài vẽ, chú ý tô màu đúng và hoàn thành bài đúng hạn.',
    'Cần rèn luyện thêm kỹ năng vẽ và tô màu để đạt yêu cầu môn Mĩ thuật.',
    'Cần chú ý hơn trong giờ học, luyện vẽ và tô màu để tiến bộ hơn.',
    'Cần cố gắng nhiều hơn, hoàn thành bài vẽ đúng hạn và tô màu cẩn thận hơn.',
    'Cần luyện tập thêm để vẽ đúng hình và tô màu đều theo yêu cầu môn học.',
  ],

  'GDTC_tot': [
    'Thực hiện đúng các động tác thể dục, tích cực tham gia luyện tập và có tiến bộ rõ rệt.',
    'Hoàn thành tốt các bài tập thể dục, có ý thức rèn luyện thể chất thường xuyên.',
    'Tham gia tích cực giờ Thể dục, thực hiện đúng động tác và có sức khỏe tốt.',
    'Học tốt môn GDTC, biết thực hiện các bài tập đúng kỹ thuật và hoàn thành đầy đủ.',
    'Nhanh nhẹn, hoạt bát, thực hiện tốt các bài tập và có ý thức rèn luyện thể chất.',
    'Có tinh thần luyện tập nghiêm túc, thực hiện đúng các động tác và có tiến bộ.',
    'Biết thực hiện các động tác cơ bản đúng kỹ thuật, tham gia đầy đủ các tiết học.',
    'Có sức khỏe tốt, thực hiện đúng các động tác và luôn hăng hái trong giờ Thể dục.',
    'Tham gia tích cực các hoạt động thể chất, thực hiện đúng động tác và có tiến bộ.',
    'Biết thực hiện các bài tập thể dục đúng hướng dẫn, có ý thức luyện tập thường xuyên.',
    'Thực hiện đúng các động tác thể dục, biết phối hợp với bạn trong các trò chơi.',
    'Có ý thức giữ gìn sức khỏe, tham gia đầy đủ các tiết học và luyện tập nghiêm túc.',
    'Nhanh nhẹn và khéo léo, thực hiện tốt các bài tập vận động và trò chơi.',
    'Biết thực hiện các động tác đúng tư thế, có tinh thần thi đua luyện tập tốt.',
    'Tham gia tích cực các trò chơi vận động, biết phối hợp nhóm và chơi đúng luật.',
    'Có thể lực tốt, thực hiện đúng các động tác và hoàn thành tốt các bài kiểm tra.',
    'Biết thực hiện các bài tập thể lực đúng kỹ thuật, có tiến bộ rõ rệt.',
    'Tham gia đầy đủ các tiết học GDTC, thực hiện đúng động tác và có ý thức luyện tập.',
    'Có tinh thần thể thao tốt, tham gia nhiệt tình và thực hiện đúng các yêu cầu.',
    'Biết giữ an toàn trong luyện tập, thực hiện đúng động tác và bảo vệ bạn bè.',
    'Thực hiện đúng các động tác thể dục sáng, có ý thức luyện tập đều đặn.',
    'Có sức bền tốt, tham gia đầy đủ các hoạt động thể chất và hoàn thành tốt.',
    'Biết thực hiện các bài tập phát triển thể lực, có tiến bộ qua từng buổi học.',
    'Tham gia tích cực các hoạt động thể dục, biết động viên bạn bè cùng luyện tập.',
    'Có ý thức rèn luyện thể chất hàng ngày, thực hiện đúng các động tác theo hướng dẫn.',
    'Biết thực hiện các động tác điều hòa, có tinh thần luyện tập nghiêm túc.',
    'Tham gia đầy đủ và tích cực, thực hiện đúng các bài tập và có tiến bộ rõ rệt.',
    'Có thể lực khá tốt, thực hiện đúng động tác và biết giúp đỡ bạn trong luyện tập.',
    'Biết thực hiện các bài tập đúng kỹ thuật, tham gia nhiệt tình và có tiến bộ.',
    'Nhanh nhẹn, thực hiện tốt các bài tập vận động và có ý thức rèn luyện thể chất.',
  ],
  'GDTC_hoan_thanh': [
    'Hoàn thành các yêu cầu môn Thể dục, cần tích cực luyện tập thêm để nâng cao thể lực.',
    'Đạt yêu cầu cơ bản môn GDTC, cần chú ý hơn trong việc thực hiện đúng các động tác.',
    'Cơ bản hoàn thành bài tập thể dục, cần cố gắng thêm để thực hiện đúng và đẹp hơn.',
    'Hoàn thành yêu cầu môn học, cần rèn thêm để thực hiện đúng kỹ thuật các động tác.',
    'Cơ bản thực hiện được các động tác, cần tích cực hơn trong các tiết học.',
    'Đã hoàn thành các bài tập, cần luyện thêm để thực hiện đúng và đều hơn.',
    'Cơ bản đạt yêu cầu, cần cố gắng thêm để nâng cao sức bền và thể lực.',
    'Hoàn thành môn GDTC, cần chú ý hơn đến việc thực hiện đúng tư thế các động tác.',
    'Đạt mức cơ bản, cần tích cực hơn trong các trò chơi vận động và luyện tập.',
    'Cơ bản hoàn thành bài tập, cần rèn thêm để thực hiện đúng và nhanh hơn.',
  ],
  'GDTC_chua_hoan_thanh': [
    'Cần tích cực hơn trong giờ Thể dục, chú ý thực hiện đúng các động tác theo hướng dẫn.',
    'Cần cố gắng hơn, tích cực tham gia luyện tập để đạt yêu cầu môn học.',
    'Cần rèn luyện thêm thể lực, chú ý thực hiện đúng các động tác và tham gia đầy đủ.',
    'Cần cố gắng nhiều hơn, tham gia tích cực và luyện tập để nâng cao thể lực.',
    'Cần chú ý hơn trong giờ học, thực hiện đúng động tác và có ý thức luyện tập.',
  ],

  'HĐTN_tot': [
    'Tham gia tích cực các hoạt động trải nghiệm, biết hợp tác và hoàn thành tốt nhiệm vụ được giao.',
    'Có ý thức tham gia hoạt động tập thể, biết chia sẻ và thể hiện sự sáng tạo trong các hoạt động.',
    'Hoàn thành tốt các yêu cầu môn HĐTN, tích cực tham gia và có tinh thần hợp tác tốt.',
    'Tham gia đầy đủ các hoạt động trải nghiệm, có ý thức xây dựng tập thể và giúp đỡ bạn bè.',
    'Năng động, sáng tạo trong các hoạt động trải nghiệm, biết chia sẻ và hỗ trợ các bạn.',
    'Hăng hái tham gia mọi hoạt động, có nhiều ý tưởng sáng tạo và hoàn thành xuất sắc nhiệm vụ.',
    'Tích cực và chủ động trong các hoạt động trải nghiệm, thể hiện tinh thần đoàn kết tốt.',
    'Luôn nhiệt tình tham gia và có đóng góp tích cực cho tập thể lớp.',
    'Biết lắng nghe và chia sẻ ý kiến trong nhóm, hoàn thành tốt nhiệm vụ được phân công.',
    'Tích cực đề xuất ý tưởng, biết phối hợp với bạn và hoàn thành hoạt động đúng hạn.',
    'Có tinh thần trách nhiệm cao, tham gia đầy đủ và hoàn thành tốt các nhiệm vụ.',
    'Biết quan sát, tìm hiểu và chia sẻ những điều học được qua các hoạt động trải nghiệm.',
    'Tham gia nhiệt tình, biết hỗ trợ bạn bè và cùng nhau hoàn thành tốt nhiệm vụ nhóm.',
    'Có ý thức xây dựng tập thể, biết đóng góp ý kiến và thực hiện tốt các hoạt động.',
    'Chủ động tham gia các hoạt động, biết sáng tạo và thể hiện bản thân tự tin.',
    'Biết phối hợp nhịp nhàng với các bạn trong nhóm, hoàn thành tốt các hoạt động tập thể.',
    'Tích cực tham gia và có nhiều đóng góp sáng tạo trong các hoạt động trải nghiệm.',
    'Có tinh thần hợp tác tốt, biết lắng nghe và tôn trọng ý kiến của bạn bè.',
    'Tham gia đầy đủ và nhiệt tình, biết chia sẻ và học hỏi qua các hoạt động.',
    'Biết vận dụng kiến thức đã học vào các hoạt động trải nghiệm thực tế.',
    'Có ý thức tham gia tích cực, biết đóng góp và hoàn thành tốt nhiệm vụ được giao.',
    'Tham gia sáng tạo và nhiệt tình, biết phối hợp với bạn để hoàn thành hoạt động.',
    'Biết thể hiện ý tưởng của mình, tham gia tích cực và hợp tác tốt với nhóm.',
    'Có tinh thần đoàn kết, biết giúp đỡ bạn và cùng nhau hoàn thành tốt nhiệm vụ.',
    'Tham gia đầy đủ các hoạt động HĐTN, biết sáng tạo và thể hiện bản thân tốt.',
    'Biết lên kế hoạch và thực hiện nhiệm vụ được giao một cách có trách nhiệm.',
    'Có ý thức học hỏi qua trải nghiệm, tham gia tích cực và chia sẻ với bạn bè.',
    'Tham gia nhiệt tình và sáng tạo, biết phối hợp nhóm và hoàn thành tốt hoạt động.',
    'Biết quan tâm đến bạn bè trong nhóm, hỗ trợ lẫn nhau để hoàn thành nhiệm vụ.',
    'Có tinh thần tích cực và sáng tạo, tham gia đầy đủ và hoàn thành tốt các yêu cầu.',
  ],
  'HĐTN_hoan_thanh': [
    'Tham gia các hoạt động trải nghiệm đúng yêu cầu, cần chủ động và sáng tạo hơn.',
    'Hoàn thành yêu cầu môn HĐTN, cần tích cực hơn trong việc tham gia và đóng góp ý kiến.',
    'Đạt yêu cầu cơ bản, cần cố gắng thêm để chủ động hơn trong các hoạt động tập thể.',
    'Cơ bản hoàn thành nhiệm vụ, cần tích cực hơn trong việc chia sẻ ý tưởng với nhóm.',
    'Hoàn thành các hoạt động đúng yêu cầu, cần rèn thêm tinh thần hợp tác và sáng tạo.',
    'Đã tham gia đầy đủ, cần chủ động hơn trong việc đề xuất ý kiến và hỗ trợ bạn.',
    'Cơ bản đạt yêu cầu, cần cố gắng thêm để thể hiện bản thân tự tin hơn.',
    'Hoàn thành môn HĐTN, cần tích cực hơn trong việc tham gia các hoạt động nhóm.',
    'Đạt mức cơ bản, cần chủ động hơn và biết chia sẻ ý tưởng với các bạn.',
    'Cơ bản hoàn thành nhiệm vụ, cần rèn thêm kỹ năng hợp tác và làm việc nhóm.',
  ],
  'HĐTN_chua_hoan_thanh': [
    'Cần tích cực hơn trong các hoạt động trải nghiệm, chủ động tham gia và hợp tác với bạn bè.',
    'Cần cố gắng hơn, chú ý tham gia đầy đủ và hoàn thành nhiệm vụ được giao.',
    'Cần chủ động hơn trong các hoạt động nhóm, biết chia sẻ và hợp tác với bạn.',
    'Cần tích cực tham gia và đóng góp ý kiến, hoàn thành đầy đủ nhiệm vụ được phân công.',
    'Cần cố gắng nhiều hơn, tham gia tích cực và biết phối hợp với bạn bè trong nhóm.',
  ],
};

if (typeof module !== 'undefined') module.exports = KHO_LOP1;
